/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Conexion;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Guada
 */
public class ConsultarInterno extends javax.swing.JPanel {

    /**
     * Creates new form PanelDerecho
     */
    Conexion con = Main.conexion;
    
    public ConsultarInterno() {
        initComponents();
        SoloNumeros(buscarDNI);
    }
    
    public void SoloNumeros(javax.swing.JTextField a){
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                char c=e.getKeyChar();
                if(!Character.isDigit(c)){
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        seleccion = new javax.swing.JComboBox<String>();
        buscarDNI = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ingrese = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(986, 580));
        setLayout(null);

        jLabel1.setText("Buscar por ");
        add(jLabel1);
        jLabel1.setBounds(10, 10, 54, 23);

        seleccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DNI", "Apellido" }));
        seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionActionPerformed(evt);
            }
        });
        add(seleccion);
        seleccion.setBounds(70, 11, 62, 20);

        buscarDNI.setColumns(20);
        buscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDNIActionPerformed(evt);
            }
        });
        add(buscarDNI);
        buscarDNI.setBounds(609, 11, 90, 20);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        add(jPanel1);
        jPanel1.setBounds(0, 40, 1170, 630);

        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(705, 10, 89, 23);

        ingrese.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ingrese.setText("Ingrese aquí el DNI:");
        add(ingrese);
        ingrese.setBounds(495, 11, 110, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionActionPerformed
        // TODO add your handling code here:
        String opcion = seleccion.getSelectedItem().toString();
                
        if("DNI".equals(opcion)){
            
            ingrese.setText("Ingrese aquí el DNI");
            buscarDNI.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {
               char caracter = e.getKeyChar();

               // Verificar si la tecla pulsada no es un digito
               if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/))
               {
                  e.consume();  // ignorar el evento de teclado
               }
            }
         });
        }
        else if("Apellido".equals(opcion)){ 
            ingrese.setText("Ingrese aquí el Apellido");
            /*buscarDNI.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {
               char caracter = e.getKeyChar();
               // Verificar si la tecla pulsada no es un digito
               if(((caracter < 'A') || (caracter > 'Z')) )
               {
                  e.consume();  // ignorar el evento de teclado
               }
            }
         });*/
        }
    }//GEN-LAST:event_seleccionActionPerformed

    private void buscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarDNIActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String campo, sql, temp;
        campo = buscarDNI.getText();
        //sql="select nombre from \"Interno\" where dni="+campo;
        FichaInterno f = new FichaInterno(campo);
        Dimension d = jPanel1.getSize();
        //System.out.println(d);
        f.setSize(d);
        f.setLocation(5,5);
               
        jPanel1.removeAll();
        jPanel1.add(f);
        jPanel1.revalidate();
        jPanel1.repaint();
        
        
        
        
        //f.setVisible(true);
        //f.setLocationRelativeTo(this);

        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarDNI;
    private javax.swing.JLabel ingrese;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> seleccion;
    // End of variables declaration//GEN-END:variables
}
