/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Dimension;

/**
 *
 * @author Luis Montenegro
 */
public class NuevoDiseño extends javax.swing.JFrame {

    /**
     * Creates new form NuevoDiseño
     */
    public NuevoDiseño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelOpciones = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        about = new javax.swing.JButton();
        consultarInterno = new javax.swing.JButton();
        registrarIngreso = new javax.swing.JButton();
        registrarEgreso = new javax.swing.JButton();
        verEstadisticas = new javax.swing.JButton();
        listarUnidad = new javax.swing.JButton();
        TituloCentral = new javax.swing.JPanel();
        Contenido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 800));

        PanelPrincipal.setLayout(null);

        PanelOpciones.setBackground(new java.awt.Color(0, 51, 102));
        PanelOpciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelOpciones.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Montenegro\\Desktop\\Escudo_de_1San_Luis_ARG.png")); // NOI18N
        PanelOpciones.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        about.setBackground(new java.awt.Color(0, 51, 153));
        about.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis Montenegro\\Desktop\\imagenes para botones\\about.png")); // NOI18N
        about.setText("jButton1");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        PanelOpciones.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 300, 60));

        consultarInterno.setBackground(new java.awt.Color(0, 51, 153));
        consultarInterno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultarinterno.png"))); // NOI18N
        consultarInterno.setText("jButton1");
        consultarInterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarInternoActionPerformed(evt);
            }
        });
        PanelOpciones.add(consultarInterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 200, 300, 60));

        registrarIngreso.setBackground(new java.awt.Color(0, 51, 153));
        registrarIngreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registraringreso.png"))); // NOI18N
        registrarIngreso.setText("jButton1");
        registrarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarIngresoActionPerformed(evt);
            }
        });
        PanelOpciones.add(registrarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 60));

        registrarEgreso.setBackground(new java.awt.Color(0, 51, 153));
        registrarEgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registraregreso.png"))); // NOI18N
        registrarEgreso.setText("jButton1");
        registrarEgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEgresoActionPerformed(evt);
            }
        });
        PanelOpciones.add(registrarEgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 60));

        verEstadisticas.setBackground(new java.awt.Color(0, 51, 153));
        verEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/verestadisticas.png"))); // NOI18N
        verEstadisticas.setText("jButton1");
        verEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verEstadisticasActionPerformed(evt);
            }
        });
        PanelOpciones.add(verEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 300, 60));

        listarUnidad.setBackground(new java.awt.Color(0, 51, 153));
        listarUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/listarporunidad.png"))); // NOI18N
        listarUnidad.setText("jButton1");
        listarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUnidadActionPerformed(evt);
            }
        });
        PanelOpciones.add(listarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 60));

        PanelPrincipal.add(PanelOpciones);
        PanelOpciones.setBounds(0, 0, 290, 801);

        TituloCentral.setBackground(new java.awt.Color(102, 153, 255));

        javax.swing.GroupLayout TituloCentralLayout = new javax.swing.GroupLayout(TituloCentral);
        TituloCentral.setLayout(TituloCentralLayout);
        TituloCentralLayout.setHorizontalGroup(
            TituloCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        TituloCentralLayout.setVerticalGroup(
            TituloCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        PanelPrincipal.add(TituloCentral);
        TituloCentral.setBounds(284, 45, 1030, 50);

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        PanelPrincipal.add(Contenido);
        Contenido.setBounds(290, 100, 990, 700);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Control de Internos del Penal de San Luis");
        PanelPrincipal.add(jLabel2);
        jLabel2.setBounds(510, 0, 490, 41);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        
    }//GEN-LAST:event_aboutActionPerformed

    private void consultarInternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarInternoActionPerformed
        ConsultarInterno pd = new ConsultarInterno();
        Dimension d = Contenido.getSize();
        //System.out.println(d);
        pd.setSize(d);
        pd.setLocation(5,5);
        Contenido.removeAll();
        Contenido.add(pd);
        Contenido.revalidate();
        Contenido.repaint();
                // TODO add your handling code here:
    }//GEN-LAST:event_consultarInternoActionPerformed

    private void registrarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarIngresoActionPerformed
        RegistrarIngreso ri = new RegistrarIngreso();
        Dimension d = Contenido.getSize();
        //System.out.println(d);
        ri.setSize(d);
        ri.setLocation(5,5);
        Contenido.removeAll();
        Contenido.add(ri);
        Contenido.revalidate();
        Contenido.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_registrarIngresoActionPerformed

    private void registrarEgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEgresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarEgresoActionPerformed

    private void verEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verEstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verEstadisticasActionPerformed

    private void listarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listarUnidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoDiseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoDiseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel PanelOpciones;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel TituloCentral;
    private javax.swing.JButton about;
    private javax.swing.JButton consultarInterno;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton listarUnidad;
    private javax.swing.JButton registrarEgreso;
    private javax.swing.JButton registrarIngreso;
    private javax.swing.JButton verEstadisticas;
    // End of variables declaration//GEN-END:variables
}
