/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Conexion;
import Logica.Management;
import static Presentacion.FichaInterno.panel_FichaInterno;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guada
 */
public class RegistrarIngreso extends javax.swing.JPanel {

    /**
     * Creates new form PanelDerecho
     */
    Conexion con = Main.conexion;
    int row;
    
    public RegistrarIngreso() {
        initComponents();
        tablaPanel.setVisible(false);
        aviso.setVisible(false);
        cargarSeleccionado.setVisible(false);
        cargarNuevo.setVisible(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        seleccion = new javax.swing.JComboBox<>();
        buscarDNI = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        tablaPanel = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();
        cargarNuevo = new javax.swing.JButton();
        aviso = new javax.swing.JLabel();
        cargarSeleccionado = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        ingrese = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        jLabel1.setText("Buscar por ");

        seleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Apellido" }));
        seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionActionPerformed(evt);
            }
        });

        buscarDNI.setColumns(20);
        buscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDNIActionPerformed(evt);
            }
        });

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos", "Nombres", "DNI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPanel.setViewportView(tablaConsulta);

        cargarNuevo.setText("Cargar datos de un Nuevo Interno");
        cargarNuevo.setEnabled(false);
        cargarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarNuevoActionPerformed(evt);
            }
        });

        aviso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cargarSeleccionado.setText("Registrar ingreso del interno Seleccionado");
        cargarSeleccionado.setEnabled(false);
        cargarSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarSeleccionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(tablaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cargarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cargarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(976, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(tablaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(cargarSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cargarNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(619, Short.MAX_VALUE))
        );

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        ingrese.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ingrese.setText("Ingrese aquí el DNI:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(ingrese, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(consultar)
                        .addComponent(ingrese)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionActionPerformed
        // TODO add your handling code here:
        String opcion = seleccion.getSelectedItem().toString();
                
        if("DNI".equals(opcion)){
            
            ingrese.setText("Ingrese aquí el DNI");
            buscarDNI.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {
               char caracter = e.getKeyChar();

               // Verificar si la tecla pulsada no es un digito
               if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/))
               {
                  e.consume();  // ignorar el evento de teclado
               }
            }
         });
        }
        else if("Apellido".equals(opcion)){ 
            ingrese.setText("Ingrese aquí el Apellido");
            /*buscarDNI.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e)
            {
               char caracter = e.getKeyChar();
               // Verificar si la tecla pulsada no es un digito
               if(((caracter < 'A') || (caracter > 'Z')) )
               {
                  e.consume();  // ignorar el evento de teclado
               }
            }
         });*/
        }
    }//GEN-LAST:event_seleccionActionPerformed

    private void buscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarDNIActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        String campo, sql, temp;
        campo = buscarDNI.getText();
        try{
            ResultSet rs = Management.consultarInternoDNI(Integer.parseInt(campo));
            if(rs.next() == false){
                tablaPanel.setVisible(false);
                cargarSeleccionado.setVisible(false);
                aviso.setText("No se encontraron Resultados...");
                cargarNuevo.setEnabled(true);
                aviso.setVisible(true);
                cargarNuevo.setVisible(true);
                jPanel1.revalidate();
                jPanel1.repaint();                
            }
            else{
                //tablaPanel.setVisible(false);
                aviso.setVisible(false);
                //cargarSeleccionado.setVisible(false);
                cargarNuevo.setVisible(false);             
                DefaultTableModel tm = (DefaultTableModel) tablaConsulta.getModel();
                int filas = tablaConsulta.getRowCount();
                for(int i=0; filas>i;i++){
                    tm.removeRow(i);
                }
                String fila[] = new String[3];
                fila[0] = rs.getString("apellido");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("dni");
                tm.addRow(fila);
                while (rs.next()) {
                    fila[0] = rs.getString("apellido");
                    fila[1] = rs.getString("nombre");
                    fila[2] = rs.getString("dni");
                    tm.addRow(fila);
                }
                tablaConsulta.setModel(tm);
                tablaPanel.setVisible(true);
                tablaPanel.repaint();
                cargarSeleccionado.setVisible(true);
                jPanel1.revalidate();
                jPanel1.repaint(); 
            }
            
        }
        catch (Exception exc) {
            System.out.println("Errorx:" + exc.getMessage());
        }
        setEventoMouseClicked(tablaConsulta);
    }//GEN-LAST:event_consultarActionPerformed

    private void cargarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarNuevoActionPerformed
        int dni = Integer.parseInt(buscarDNI.getText());
        FichaInterno f = new FichaInterno(dni);
        Dimension d = jPanel1.getSize();
        f.setSize(d);        
        f.setLocation(5,5);
        
               
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        jLabel1.setVisible(false);
        seleccion.setVisible(false);
        ingrese.setVisible(false);
        buscarDNI.setVisible(false);
        consultar.setVisible(false);
        
        jPanel1.add(f);
        jPanel1.revalidate();
        jPanel1.repaint();
        

    }//GEN-LAST:event_cargarNuevoActionPerformed

    private void cargarSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarSeleccionadoActionPerformed
        int dni = Integer.parseInt(buscarDNI.getText());
        FichaInterno f = new FichaInterno(dni);
        Dimension d = jPanel1.getSize();
        f.setSize(d);        
        f.setLocation(5,5);
        
               
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
        jLabel1.setVisible(false);
        seleccion.setVisible(false);
        ingrese.setVisible(false);
        buscarDNI.setVisible(false);
        consultar.setVisible(false);
        panel_FichaInterno.setSelectedIndex(1);
        jPanel1.add(f);
        jPanel1.revalidate();
        jPanel1.repaint();
        
    }//GEN-LAST:event_cargarSeleccionadoActionPerformed

    private void setEventoMouseClicked(JTable tablaConsulta) {
        tablaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                tablaMouseClicked(e);
            }

            private void tablaMouseClicked(MouseEvent e) {
                row = tablaConsulta.getSelectedRow();
                if (row != -1  ){
                    cargarSeleccionado.setEnabled(true);
                }else{
                    cargarSeleccionado.setEnabled(false);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JTextField buscarDNI;
    private javax.swing.JButton cargarNuevo;
    private javax.swing.JButton cargarSeleccionado;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel ingrese;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> seleccion;
    private javax.swing.JTable tablaConsulta;
    private javax.swing.JScrollPane tablaPanel;
    // End of variables declaration//GEN-END:variables
}
